### ISSUE TITLE
Kernel.const_set, seriously?

### ISSUE THREAD

**Issue by quaternion** [railsconfig/config#122]
The Kernel module is included by class Object, so its methods are available in **every Ruby object**.

Result:

``` ruby
Module::Settings #=> #<Config::Options ... >
Class::Settings #=> #<Config::Options ... >
nil::Settings #=> #<Config::Options ... >
ActiveRecord::Base::Settings #=> #<Config::Options ... >
```

**Comment by pkuczynski** [comment]
How would you suggest to implement it differently?

**Comment by malakai97** [comment]
Anyone who needs this to be loaded into the global namespace by another name should just do it themselves.  It's a trivial assignment.
```ruby
require "config"
MySettings = Config
```

I suggest removing this feature.

**Comment by quaternion** [comment]
Through definition a custom class or module:
```ruby
class Settings < Config::Base
end
```
or
```ruby
class Settings
  include Config
end
```

**Comment by pkuczynski** [comment]
You are totally right that Kernel.const_set is not the best way to expose settings. This was in the code, before I joined the project and I never really thought about it before... There are couple of problems with the current setup actually. First of all Config is a module which holds the logic of loading settings, while what you referring to is a static OpenStruct object called Settings, holding all the values for settings - so they two different things and neither of the solutions you described above would work.

I actually never liked this split and always thought it should be a single object. Additionally its confusing with config as a gem name and object used to wire things up, while actually values are accessed via Settings instance. Config also conflicts with some old object name and raise a warning...

I do not have anything fixed in mind how to solve this, as I assume original gem author wanted to keep Settings slim...

I will have to think about it... Any suggestions welcome...

**Comment by baarde** [comment]
Regarding the problem of exposing `Settings` in every module, I think you can fix that by replacing `Kernel` with `Object`.

```
irb(main):001:0> One = 1
=> 1
irb(main):002:0> ::One
=> 1
irb(main):003:0> Object::One
=> 1
irb(main):004:0> ActiveRecord::Base::One
Traceback (most recent call last):
        1: from (irb):4
NameError (uninitialized constant ActiveRecord::Base::One)
irb(main):005:0> 
irb(main):006:0> Object.const_set 'Two', 2
=> 2
irb(main):007:0> ::Two
=> 2
irb(main):008:0> Object::Two
=> 2
irb(main):009:0> ActiveRecord::Base::Two
Traceback (most recent call last):
        1: from (irb):9
NameError (uninitialized constant ActiveRecord::Base::Two)
irb(main):010:0> 
```

See [Stack Overflow: Ruby, how to reference Root namespace?](https://stackoverflow.com/questions/21263054/ruby-how-to-reference-root-namespace)

**Comment by pkuczynski** [comment]
Fixed
