### ISSUE TITLE
files to be ignored in .gitignore should be with slash?

### ISSUE THREAD

**Issue by gipcompany** [railsconfig/config#133]
When I did `rails g config:install ` as described in README.md, I saw the following diff in .gitignore file.

```
diff --git a/.gitignore b/.gitignore
index 5b61ab0..f9501c9 100644
--- a/.gitignore
+++ b/.gitignore
@@ -11,3 +11,7 @@
 /log/*
 !/log/.keep
 /tmp
+
+config/settings.local.yml
+config/settings/*.local.yml
+config/environments/*.local.yml

```

However, I think the files to be added should be with slash on the top as follows. What do you think of this?

```
+
+/config/settings.local.yml
+/config/settings/*.local.yml
+/config/environments/*.local.yml

```

**Comment by pkuczynski** [comment]
I do not think this is necessary. Did you encounter any problem when the path does not start from root (slash)?

**Comment by xHire** [comment]
You're right that there's very small probability that it could match some unrelated files. I can imagine `/test/fixtures/files/config/settings.local.yml` or something like that. :c) But for purity, the slash should definitely be there. Because **if** it happens, it might be tricky to track down the reason.

**Comment by xHire** [comment]
You're right that there's very small probability that it could match some unrelated files. I can imagine `/test/fixtures/files/config/settings.local.yml` or something like that. :c) But for purity, the slash should definitely be there. Because **if** it happens, it might be tricky to track down the reason.

**Comment by xHire** [comment]
You're right that there's very small probability that it could match some unrelated files. I can imagine `/test/fixtures/files/config/settings.local.yml` or something like that. :c) But for purity, the slash should definitely be there. Because **if** it happens, it might be tricky to track down the reason.

**Comment by pkuczynski** [comment]
The thing is that you want the local files not to be comitable, as they only for local developer :)

**Comment by xHire** [comment]
Exactly. :c) But this gem should affect only files relating to this gem. That's why slashes should be there.
