### ISSUE TITLE
Byte calculations do not work (x.megabytes, x.gigabytes, etc)

### ISSUE THREAD

**Issue by uberllama** [railsconfig/config#19]
I tried to implement a settings as follows:
    threshold: <%=10.megabytes%>
    max: <%=1.gigabyte%>

...but it doesn't seem to be supported. Not using ERB tags results in a string.

**Comment by pkuczynski** [comment]
@rdubya could we pass YAML file trough ruby engine before loading it? This could be a nice feature, what you think?

**Comment by rdubya** [comment]
Doesn't it already get ran through ERB? Seems like this is an issue with dependencies not being loaded since those methods come from ActiveSupport iirc

**Comment by supremebeing7** [comment]
This already seems to work on 2.0.0, I just verified. Since this issue was filed 8 years ago, maybe @uberllama's version didn't support ERB?
However, I did run into a different issue that may be related: `max` and `min` appear to be reserved words and will behave unexpectedly.
```yaml
settings_group:
  max: "max"
  min: "min"
  other: "other"
```
```ruby
> Settings.settings_group.max
=> [:other, "other"]
> Settings.settings_group.min
=> [:max, "max"]
> Settings.settings_group.other
=> "other"
```
I'm going to file a separate issue for that, but seems like this issue can be closed.

**Comment by supremebeing7** [comment]
https://github.com/railsconfig/config/issues/234

**Comment by uberllama** [comment]
I can't remember what I had for breakfast this morning, let alone what bugs I had 8 years ago. 😂

**Comment by pkuczynski** [comment]
Hahaha, indeed :) Haven't noticed it's so old :) I will close this one and look into #234 separately.
