### ISSUE TITLE
Using rails_config in config/environments/*.rb

### ISSUE THREAD

**Issue by jandudulski** [railsconfig/config#32]
Hi!

I know, there was some issues like that before, but it looks that it happen again. Works for me with 0.2.5, broken above. Ruby 1.9.2, rails 3.2.2

```
/path/to/project/config/environments/development.rb:33:in `block in <top (required)>': uninitialized constant Settings (NameError)
```

**Comment by hulkakshay** [comment]
i am facing the same issue, here what happens when is run..
bundle exec rake daemons:start 

rake aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'mysql2'.
Gem Load Error is: uninitialized constant Mysql2::Client::SECURE_CONNECTION
Backtrace for gem load error is:
/home/viru/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/mysql2-0.3.15/lib/mysql2/client.rb:12:in `<class:Client>'
/home/viru/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/mysql2-0.3.15/lib/mysql2/client.rb:2:in `<module:Mysql2>'
/home/viru/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/mysql2-0.3.15/lib/mysql2/client.rb:1:in `<top (required)>'
/home/viru/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/mysql2-0.3.15/lib/mysql2.rb:10:in `require'
/home/viru/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/mysql2-0.3.15/lib/mysql2.rb:10:in `<top (required)>'
/home/viru/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.15.3/lib/bundler/runtime.rb:82:in `require'
/home/viru/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.15.3/lib/bundler/runtime.rb:82:in `block (2 levels) in require'
/home/viru/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.15.3/lib/bundler/runtime.rb:77:in `each'
/home/viru/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.15.3/lib/bundler/runtime.rb:77:in `block in require'
/home/viru/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.15.3/lib/bundler/runtime.rb:66:in `each'
/home/viru/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.15.3/lib/bundler/runtime.rb:66:in `require'
/home/viru/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.15.3/lib/bundler.rb:108:in `require'
/home/viru/peatio/config/application.rb:12:in `<top (required)>'
/home/viru/peatio/Rakefile:5:in `require'
/home/viru/peatio/Rakefile:5:in `<top (required)>'
/home/viru/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load'
/home/viru/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load_rakefile'
/home/viru/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:689:in `raw_load_rakefile'
/home/viru/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:94:in `block in load_rakefile'
/home/viru/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/home/viru/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:93:in `load_rakefile'
/home/viru/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:77:in `block in run'
/home/viru/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/home/viru/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/home/viru/.rbenv/versions/2.2.1/bin/rake:33:in `<top (required)>'
/home/viru/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.15.3/lib/bundler/cli/exec.rb:74:in `load'
/home/viru/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.15.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/viru/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.15.3/lib/bundler/cli/exec.rb:27:in `run'
/home/viru/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.15.3/lib/bundler/cli.rb:365:in `exec'
/home/viru/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/viru/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/viru/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
/home/viru/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.15.3/lib/bundler/cli.rb:22:in `dispatch'
/home/viru/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
/home/viru/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.15.3/lib/bundler/cli.rb:13:in `start'
/home/viru/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.15.3/exe/bundle:30:in `block in <top (required)>'
/home/viru/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.15.3/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/home/viru/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.15.3/exe/bundle:22:in `<top (required)>'
/home/viru/.rbenv/versions/2.2.1/bin/bundle:23:in `load'
/home/viru/.rbenv/versions/2.2.1/bin/bundle:23:in `<main>'
Bundler Error Backtrace:
/home/viru/peatio/config/application.rb:12:in `<top (required)>'
/home/viru/peatio/Rakefile:5:in `require'
/home/viru/peatio/Rakefile:5:in `<top (required)>'
/home/viru/.rbenv/versions/2.2.1/bin/bundle:23:in `load'
/home/viru/.rbenv/versions/2.2.1/bin/bundle:23:in `<main>'
NameError: uninitialized constant Mysql2::Client::SECURE_CONNECTION
/home/viru/peatio/config/application.rb:12:in `<top (required)>'
/home/viru/peatio/Rakefile:5:in `require'
/home/viru/peatio/Rakefile:5:in `<top (required)>'
/home/viru/.rbenv/versions/2.2.1/bin/bundle:23:in `load'
/home/viru/.rbenv/versions/2.2.1/bin/bundle:23:in `<main>'
ubuntu 16.04 OS
mysql 5.6 distrb
mysql2 (0.3.15)
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]

please help me out.
Thanks

**Comment by hulkakshay** [comment]
Does the issue is because of ubuntu 16.04 as the peatio installation has mentioned that it officially supports

    Ubuntu Linux 14.04 LTS
    Mac OS X Mavericks
