### ISSUE TITLE
passing variables

### ISSUE THREAD

**Issue by dudo** [railsconfig/config#90]
I'm wondering if we can pass variables like we can with the locale files, using `#{var}` in the yaml file. 

    Settings.foo.bar(var: 'baz')

?

**Comment by dudo** [comment]
I just googled this issue... and here is my original request. Kinda funny...

**Comment by pkuczynski** [comment]
I am not entirely sure what would you like to achieve here? Settings is for reading values, so why would you expect `bar` to be a method which you can call?

**Comment by dudo** [comment]
Are you familiar with the I18n locales? Same reason. Being able to inject
something into the middle of a value.

**Comment by pkuczynski** [comment]
Do you mean calling `t('welcome.text', myvar)`? then i18n YAML file is static, but they use I18n module method to inject variables:

http://guides.rubyonrails.org/i18n.html#passing-variables-to-translations

Unless I am missing something here?

**Comment by dudo** [comment]
Sure. But I use rails config to have different words/values per
environment. Locales don't work for me there, unless I chunked them
together under the env name, I guess...

Config uses erb... But no thoughts on passing an argument, huh? I guess it
could be overkill. Thanks for the time, you can close.

**Comment by pkuczynski** [comment]
I believe if you need extrapolate the setting value, you should to that on the code level, as I can only imagine the value you need to pass would have to be provided in run-time...

We could obviously add a method like `Config.read('welcome.text', myvar)`, which you could call instead of `Config.welcome.text`, if thats what you are looking for? But I am not entirely sure of this is the right approach?

I will close for now but feel free to add something if you want....
